unstable_features = true

imports_layout = "Horizontal"
match_arm_blocks = false
match_block_trailing_comma = true
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = true
struct_lit_single_line = false
tab_spaces = 2
trailing_comma = "Never"
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true